title: Pluto Mingyu's Observatory
logo: /assets/img/logo.jpg
email: lmg141511@gmail.com
description: Aerospace Engineer\nAI & Big Data Engineer\nAmateur astronomer\n\nCNN(Convolutional Neural Network)\nBig data analysis\nStar-Galaxy Separation Problem\nAstronomical Datasets
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/mingyupluto
  - name: Instagram
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://www.instagram.com/pluto_mingyu

navigation:
  - name: Abouut
    link: ./about.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
