title: Pluto Mingyu's Observatory
logo: /assets/img/logo.jpg
email: lmg141511@gmail.com
description: Aerospace and AI & Big Data Engineer, My research interests are CNN(Convolutional Neural Network) to solve the SGCP, and producing high-performance astronomical image datasets.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/mingyupluto
  - name: Instagram
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://www.instagram.com/pluto_mingyu

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
